apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherkube-worker.fullname" . }}
  labels:
    app: {{ include "aetherkube-worker.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "aetherkube-worker.name" . }}
  ports:
    - name: dummy
      port: 80
      targetPort: 80
