apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherkube-web.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aetherkube-web.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
