apiVersion: v1
kind: Service
metadata:
  name: aetherkube-web
  namespace: staging
spec:
  selector:
    app: aetherkube-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
